apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: nginx-ds
spec:
  selector:
    matchLabels:
      app: nginx-pod
  template:
    metadata:
      name: nginx-pod
      labels:
        app: nginx-pod
    spec: 
      nodeSelector:
          name:node1
      containers:
        - name: webserver
          image: nginx
          ports:
          - containerPort: 80	