apiVersion: v1
kind: Service
metadata:
   name: simple-svc
spec:
   selector:
      app:nginx
   type: NodePort
   ports:
      - name: http
        port: 81
        nodePort: 30001
        portocol: TCP  